name: Build ESP32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Espressif (ESP-IDF) Build Action
      uses: HareshPrajapati/esp_idf_build_action@V2
      with:
        esp_idf_version: 'v5.0.1'
        target: 'esp32s3'
        path: '.'

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/*.bin
            build/*.elf
            build/bootloader/bootloader.bin

